### ISSUE TITLE
Mission Making Script Errors

### ISSUE THREAD

**Issue by Sim-ian** [Herbiie/ArmAReforgerMissionMakingGuide#1]
Hi

I have been following your Mission Making tutorial and got to the script section for ending the mission. following the instructions when Validating the code i get an error on the "override bool ScriptedEntityFilterForQuery(IEntity ent) {" line stating that the function is marked as an override but no other function in the base class with that name.

I initially overcame by removing the override statement but then i got an error further down on line 12...

The new error is "Undefined function 'CompletionTest_Class.IsAlive'" which i can't guess how to fix.

So either Bohemia have changed something since you wrote this guide or something is missing, I have checked and i don't think i missed any of the steps following the tutorial.

Would be interested in a solution or at least your take on the issue.

**Comment by Vardeno** [comment]
Hi,

I'm not at my home computer now to make the propert tests, but I can't find "CompletionTest_Class.IsAlive" in the code provied with the tutorial. Can you show us your code?

In other hand, if the compiler is saying that "ScriptedEntityFilterForQuery" isn't overriding a functión maybe your class doesn't hinerit the proper super class. Check that your first line is something llike "class Your_Class : SCR_BaseTriggerEntity"

**Comment by Sim-ian** [comment]
Hi

CompletionTest is the name of my script so i would assume it's the Class.IsAlive that its not finding.

The first line is as it was put in generating the trigger script...

class CompletionTest_Class: BaseGameTriggerEntity 

This is the complete code as pasted from the PasteBin link in the tutorial, the only addition is the class declaration added when you generate the userScript i.e. the first line.

`class CompletionTest_Class: BaseGameTriggerEntity 
{
	// user script
    protected int m_iCount; // keep count of enemies
    
    // Set up the filter
    override bool ScriptedEntityFilterForQuery(IEntity ent) {
        SCR_ChimeraCharacter cc = SCR_ChimeraCharacter.Cast(ent);
        if (!cc) return false; // If the entity is not a person, filter it out
        if (cc.GetFactionKey() != "USSR") return false; // If the entity does not have the Faction key of USSR, filter it out
        if (!IsAlive(cc)) return false; // If the entity is dead, filter it out
        return true; // Otherwise, include it!
    }
    
    override void OnActivate(IEntity ent)
    {
        ++m_iCount; // When activated (i.e. when an alive USSR soldier entity enters), add 1 to the number m_iCount
    }
    
    override void OnDeactivate(IEntity ent)
    {        
        --m_iCount; // When deactivated (i.e. if the soldier leaves or dies) take away 1 to the number m_iCount
        if (m_iCount <= 5) // if m_iCount is now at 5 (or less than 5), run the OnEmptied function below. Change this from 0 to avoid the endless hunt for the last few Ivans
            OnEmptied();
    }
    
    void OnEmptied()
    {
        SCR_BaseGameMode gameMode = SCR_BaseGameMode.Cast(GetGame().GetGameMode()); // Get the game mode for the end script
        Faction faction = GetGame().GetFactionManager().GetFactionByKey("US"); // Get the winning faction Key
        int usIndex = GetGame().GetFactionManager().GetFactionIndex(faction); // Get the winning faction key's index
        gameMode.EndGameMode(SCR_GameModeEndData.CreateSimple(SCR_GameModeEndData.ENDREASON_EDITOR_FACTION_VICTORY, -1, usIndex)); // End the mission!
    }

};
`

**Comment by Vardeno** [comment]
Ok, I havn't tested the tutorial yet, so I can't confirm that it works. I'll try later when I get home if I can. But it seems that maybe something has changed in the last update.

I'm afraid that these kind of problems are going to be quite common until the game has a stable versión. And until we have a proper wiki an API it wont be easy to fix them.

I'm sorry I cant be of more help.

**Comment by Sim-ian** [comment]
No problem, I initially assumed it could be due to updates just trying to get my head around creating missions from scratch rather than jus recreating Capture & Hold all the time.

**Comment by Herbiie** [comment]
I will look into it when I am back at my PC, may have been broken in the update.

IsAlive was defined already in the base trigger.

**Comment by Herbiie** [comment]
> Hi
> 
> CompletionTest is the name of my trigger so i would assume it's the Class.IsAlive that its not finding.
> 
> The first line is as it was put in generating the trigger script...
> 
> class CompletionTest_Class: BaseGameTriggerEntity
> 
> This is the complete code as pasted from the PasteBin link in the tutorial, the only addition is the class declaration added when you generate the userScript i.e. the first line.
> 
> ```
> class CompletionTest_Class: BaseGameTriggerEntity 
> {
> 	// user script
>     protected int m_iCount; // keep count of enemies
>     
>     // Set up the filter
>     override bool ScriptedEntityFilterForQuery(IEntity ent) {
>         SCR_ChimeraCharacter cc = SCR_ChimeraCharacter.Cast(ent);
>         if (!cc) return false; // If the entity is not a person, filter it out
>         if (cc.GetFactionKey() != "USSR") return false; // If the entity does not have the Faction key of USSR, filter it out
>         if (!IsAlive(cc)) return false; // If the entity is dead, filter it out
>         return true; // Otherwise, include it!
>     }
>     
>     override void OnActivate(IEntity ent)
>     {
>         ++m_iCount; // When activated (i.e. when an alive USSR soldier entity enters), add 1 to the number m_iCount
>     }
>     
>     override void OnDeactivate(IEntity ent)
>     {        
>         --m_iCount; // When deactivated (i.e. if the soldier leaves or dies) take away 1 to the number m_iCount
>         if (m_iCount <= 5) // if m_iCount is now at 5 (or less than 5), run the OnEmptied function below. Change this from 0 to avoid the endless hunt for the last few Ivans
>             OnEmptied();
>     }
>     
>     void OnEmptied()
>     {
>         SCR_BaseGameMode gameMode = SCR_BaseGameMode.Cast(GetGame().GetGameMode()); // Get the game mode for the end script
>         Faction faction = GetGame().GetFactionManager().GetFactionByKey("US"); // Get the winning faction Key
>         int usIndex = GetGame().GetFactionManager().GetFactionIndex(faction); // Get the winning faction key's index
>         gameMode.EndGameMode(SCR_GameModeEndData.CreateSimple(SCR_GameModeEndData.ENDREASON_EDITOR_FACTION_VICTORY, -1, usIndex)); // End the mission!
>     }
> 
> };
> ```
> 
> Removing the override on the first line in the //Set up filter section overcomes the initial error but i don't know if it would work without the override but the IsAlive issue i have no clue about.

You're just deleting the filter there so this won't work.

**Comment by SneakyAzWhat** [comment]
Try using 'SCR_BaseTriggerEntity' instead of 'BaseGametriggerEntity' and let me know if that fixes it for you

**Comment by Vardeno** [comment]
> Try using 'SCR_BaseTriggerEntity' instead of 'BaseGametriggerEntity' and let me know if that fixes it for you. It looks like you selected the wrong trigger so line 1 was generated (inheriting from BaseGameTriggerEntity class) from a class that doesn't have IsAlive() as an available method/function. Creating a trigger from 'SCR_BaseTriggerEntity' will fix the problem, no need to change the script as everything in it appears fine at a glance.
> 
> PS - Make sure when you create this trigger in the hierarchy you are selecting 'SCR_BaseTriggerEntity', here is a video with timestamp if you need to see what i mean: https://youtu.be/2BM7stNyaNk?t=1266

Yep, that's what I was looking when I ask him to show us the code. If the compiler sais there is no method to override, then he have inherit the wrong class. I totally missed that he used BaseGameTriggerEntity.

That should fix the problem.

**Comment by Herbiie** [comment]
> Try using 'SCR_BaseTriggerEntity' instead of 'BaseGametriggerEntity' and let me know if that fixes it for you. It looks like you selected the wrong trigger so line 1 was generated (inheriting from BaseGameTriggerEntity class) from a class that doesn't have IsAlive() as an available method/function. Creating a trigger from 'SCR_BaseTriggerEntity' will fix the problem, no need to change the script as everything in it appears fine at a glance.
> 
> PS - Make sure when you create this trigger in the hierarchy you are selecting 'SCR_BaseTriggerEntity', here is a video with timestamp if you need to see what i mean: https://youtu.be/2BM7stNyaNk?t=1266

Thanks Sneaky! I'll add a note to the tutorial to make sure people are adding the right trigger entity.
