### ISSUE TITLE
Please rename the Wiki pages, because impossible to clone them

### ISSUE THREAD

**Issue by cr0ssmind** [Herbiie/ArmAReforgerMissionMakingGuide#2]
Because it has special characters ")" in the page names, impossible to clone them.

`error: unable to create file 1)--ArmA-Reforger-Mission-Making-|-Getting-Started.md: Invalid argument
error: unable to create file 2)-ArmA-Reforger-Mission-Making-|-Creating-The-Mission.md: Invalid argument
error: unable to create file 3)--ArmA-Reforger-Mission-Making-|-Finishing-The-Mission.md: Invalid argument
error: unable to create file 4)-ArmA-Reforger-Mission-Making-|-Extras.md: Invalid argument
fatal: unable to checkout working tree
`

**Comment by Herbiie** [comment]
Clone them where?

**Comment by Herbiie** [comment]
Shouldn't be any need to clone the GitHub, closing.

**Comment by cr0ssmind** [comment]
Fyi, here:

![image](https://user-images.githubusercontent.com/3390151/170740898-d3b072f9-0744-4895-95a7-acb08aef2bb5.png)
